server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://91.196.245.199:5432/sprellotest
    username: ${psql_login}
    password: ${psql_password}
  jpa:
    generate-ddl: true

security:
  oauth2:
    client:
      clientId: 1047025068395-jpvl32v8et5hnp7dgg4v06dj1g6ss1f5.apps.googleusercontent.com
      clientSecret: 0vBdEE_5zMD0qLqNqpMng8i2
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
